language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libgtest-dev

before_install:
- export CC=gcc-7
- export CXX=g++-7

script:
- ./configure --examples --tests --benchmarks
- make
- make test
